In [ ]:
import pandas as pd
df = pd.read_csv('Re_Data.csv')
df = df.iloc[0:5000]
#for the sake of making it easier to run

df

clean_comment  category
0      family mormon have never tried explain them t...  Positive
1     buddhism has very much lot compatible with chr...  Positive
2     seriously don say thing first all they won get...  Negative
3     what you have learned yours and only yours wha...   Neutral
4     for your own benefit you may want read living ...  Positive
...                                                 ...       ...
4995      this has been enlightening cultural exchange   Positive
4996           dont even belong here but this much fun   Positive
4997   the whiskey this really out left field clint ...  Positive
4998  aaron barrett performance tonight related this...   Neutral
4999                                    flair thenewse    Neutral

[5000 rows x 2 columns]

In [ ]:
import numpy as np
df = df.replace(np.nan, ' ', regex=True)

In [ ]:
import string
df['clean_comment'] = df['clean_comment'].str.replace('[^\w\s]','')
df

clean_comment  category
0      family mormon have never tried explain them t...  Positive
1     buddhism has very much lot compatible with chr...  Positive
2     seriously don say thing first all they won get...  Negative
3     what you have learned yours and only yours wha...   Neutral
4     for your own benefit you may want read living ...  Positive
...                                                 ...       ...
4995      this has been enlightening cultural exchange   Positive
4996           dont even belong here but this much fun   Positive
4997   the whiskey this really out left field clint ...  Positive
4998  aaron barrett performance tonight related this...   Neutral
4999                                    flair thenewse    Neutral

[5000 rows x 2 columns]

In [ ]:
df.clean_comment = df.clean_comment.str.replace('\d+', '')
df

clean_comment  category
0      family mormon have never tried explain them t...  Positive
1     buddhism has very much lot compatible with chr...  Positive
2     seriously don say thing first all they won get...  Negative
3     what you have learned yours and only yours wha...   Neutral
4     for your own benefit you may want read living ...  Positive
...                                                 ...       ...
4995      this has been enlightening cultural exchange   Positive
4996           dont even belong here but this much fun   Positive
4997   the whiskey this really out left field clint ...  Positive
4998  aaron barrett performance tonight related this...   Neutral
4999                                    flair thenewse    Neutral

[5000 rows x 2 columns]

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [ ]:
from nltk.stem.snowball import PorterStemmer

In [ ]:
ps = PorterStemmer()
for i in range(0, len(df)):
  df.clean_comment[i] = ps.stem(df.clean_comment[i]) 

df

clean_comment  category
0      family mormon have never tried explain them t...  Positive
1     buddhism has very much lot compatible with chr...  Positive
2     seriously don say thing first all they won get...  Negative
3     what you have learned yours and only yours wha...   Neutral
4     for your own benefit you may want read living ...  Positive
...                                                 ...       ...
4995      this has been enlightening cultural exchange   Positive
4996           dont even belong here but this much fun   Positive
4997   the whiskey this really out left field clint ...  Positive
4998  aaron barrett performance tonight related this...   Neutral
4999                                    flair thenewse    Neutral

[5000 rows x 2 columns]

In [ ]:
df['category'].value_counts()

Positive    2257
Neutral     1633
Negative    1110
Name: category, dtype: int64

In [ ]:
x = df['category'].values
y = df['clean_comment'].values

print(y)

[' family mormon have never tried explain them they still stare puzzled from time time like some kind strange creature nonetheless they have come admire for the patience calmness equanimity acceptance and compassion have developed all the things buddhism teaches '
 'buddhism has very much lot compatible with christianity especially considering that sin and suffering are almost the same thing suffering caused wanting things shouldn want going about getting things the wrong way christian this would mean wanting things that don coincide with god will and wanting things that coincide but without the aid jesus buddhism could also seen proof god all mighty will and omnipotence certainly christians are lucky have one such christ there side but what about everyone else well many christians believe god grace salvation and buddhism god way showing grace upon others would also help study the things jesus said and see how buddha has made similar claims such rich man getting into heaven joke basica

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3, random_state = 0)

In [ ]:
import numpy as np

In [ ]:
np.unique(y_train,return_counts=True)

(array(['', '\n',
        '\najay maken   last hrs all channels showing bjp ahead counting now showing correct picture they changed but who change their affiliations ',
        ..., 'この情報ってどうやって入手出来たのですか', '吸我的公鸡', '日本語でお願いできますか'], dtype=object),
 array([3, 1, 1, ..., 1, 1, 1]))

In [ ]:
np.unique(y_test,return_counts=True)

(array(['',
        '\nthey have the gun based nypd will release the sources comey doesn ',
        ' ', ..., 'zing zing zing zing zing zing zingaat ',
        'zon kuthon and his sister shelyn good deity have really cool story from the pathfinder setting plus off topic pathfinder has the coolest good deity ever cayden cailean was bard that got wasted one night stumbled into the temple the star stone artifact that can turn you into deity and woke the next morning with hangover memory the night before and godly powers ',
        '日本語で投稿してもていただけますでしょうか そうしたら私が翻訳させていただきます'], dtype=object),
 array([ 1,  1, 15, ...,  1,  1,  1]))

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC

In [ ]:
text_model = Pipeline([('tfidf',TfidfVectorizer()),('model',SVC())]) 

text_model.fit(x_train, y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('model',
                 SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None,
                     coef0=0.0, decision_function_shape='ovr', d

In [ ]:
y_pred = text_model.predict(x_test)
y_pred

array(['excellent post ', 'zelalem passing makes hard ',
       'zelalem passing makes hard ', ..., ' ', 'excellent post ',
       'zelalem passing makes hard '], dtype=object)

In [ ]:
np.unique(y_pred,return_counts=True)

(array([' ', 'excellent post ', 'zelalem passing makes hard '],
       dtype=object), array([493, 658, 349]))

In [ ]:
y_test

array([' modi divisive figure people like call him you will get strong opinions from both sides and zero facts the same time the principle political opponent the nehru gandhi family with strong dynasty influence inc unifying figure where there global agreement that they are themselves highly corrupt and shelter the corrupt and the sole purpose they serve that indian national congress party would disintegrate the absence sycophancy some people strongly believe that having dumbass with zero track record experience governance much more preferable compared someone who may may not been responsible for sheltering the rioters each their own ',
       'more than the this could game changer eliminating petty corruption which adds gargantuan numbers take the mnrega good scheme long the money reaches the target and there asset creation happening parallely various studies have estimated that only the allocated money even reaches the intended audience the rest being swallowed along the way this wor

In [ ]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [ ]:
accuracy_score(y_pred,y_test)*100

0.7333333333333333

In [ ]:
confusion_matrix(y_pred,y_test)

array([[11,  1,  1, ...,  0,  1,  1],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0]])

In [ ]:
print(classification_report(y_pred,y_test))

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [ ]:
text_model.predict(["The room was kind of clean but had a VERY strong smell of dogs Generally below average but ok for a overnight stay if youre not too fussy Would consider staying again if the price was right Breakfast was free and just about better than nothing"])

array([' '], dtype=object)

In [28]:
%%writefile app.py
import streamlit as st
st.title('Sentiment Analysis using Python')
import pandas as pd
df = pd.read_csv('Re_Data.csv')
df = df.iloc[0:5000]
import numpy as np
df = df.replace(np.nan, ' ', regex=True)
import string
df['clean_comment'] = df['clean_comment'].str.replace('[^\w\s]','')
df.clean_comment = df.clean_comment.str.replace('\d+', '')
import nltk
nltk.download('punkt')
nltk.download('wordnet')
from nltk.stem.snowball import PorterStemmer
ps = PorterStemmer()
for i in range(0, len(df)):
  df.clean_comment[i] = ps.stem(df.clean_comment[i]) # for word in df.clean_comment[i]]
x = df['category'].values
y = df['clean_comment'].values
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3, random_state = 0)
import numpy as np
np.unique(y_train,return_counts=True)
np.unique(y_test,return_counts=True)
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
text_model = Pipeline([('tfidf',TfidfVectorizer()),('model',SVC())]) 
text_model.fit(x_train, y_train)
y_pred = text_model.predict(x_test)
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
select = st.text_input('Enter your message')
op = text_model.predict([select])
st.title(op[0])
if op[0] == "Positive":
  st.title(op)
  st.title(emoji.emojize(':smile:'))
elif op[0]=="Neutral":
  st.title(op)
  st.title(emoji.emojize(':expressionless:'))
elif op[0]=="Negative":
  st.title(op)
  st.title(emoji.emojize(':worried:'))

Overwriting app.py


In [1]:
!pip install streamlit
!pip install pyngrok==4.1.1
from pyngrok import ngrok
!pip install emoji

In [4]:
%%writefile app.py
import streamlit as st
st.title('Sentiment Analysis')
import pandas as pd
import emoji
df = pd.read_csv('Re_Data.csv')
df =df.iloc[0:5000]
df.dropna(inplace=True)
import string
df['clean_comment'] = df['clean_comment'].str.replace('[^\w\s]','')
df.clean_comment = df.clean_comment.str.replace('\d+','')
x = df.iloc[:,0]
y = df.iloc[:,1]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3, random_state = 0)
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
text_model = Pipeline([('tfidf',TfidfVectorizer()),('model',SVC())]) 
text_model.fit(x_train, y_train)
select = st.text_input('Enter your message')
op = text_model.predict([select])
if op[0] == "Positive":
  st.title(op)
  st.title(emoji.emojize(':smile:'))
elif op[0]=="Neutral":
  st.title(op)
  st.title(emoji.emojize(':expressionless:'))
elif op[0]=="Negative":
  st.title(op)
  st.title(emoji.emojize(':worried:'))

Overwriting app.py


In [2]:
!nohup streamlit run app.py &
url = ngrok.connect(port='8501')
url

nohup: appending output to 'nohup.out'


'http://ec519aae065c.ngrok.io'